//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX.CTI.SMSWS.CTCSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ws.dahantc.com", ConfigurationName="CTCSmsService.ISmsService4XML")]
    public interface ISmsService4XML {
        
        [System.ServiceModel.OperationContractAttribute(Action="balance", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string balance(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="deliver", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string deliver(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="submit", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string submit(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="report", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string report(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="keywordcheck", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string keywordcheck(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="blackListCheck", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string blackListCheck(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsService4XMLChannel : FX.CTI.SMSWS.CTCSmsService.ISmsService4XML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsService4XMLClient : System.ServiceModel.ClientBase<FX.CTI.SMSWS.CTCSmsService.ISmsService4XML>, FX.CTI.SMSWS.CTCSmsService.ISmsService4XML {
        
        public SmsService4XMLClient() {
        }
        
        public SmsService4XMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsService4XMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsService4XMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsService4XMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string balance(string message) {
            return base.Channel.balance(message);
        }
        
        public string deliver(string message) {
            return base.Channel.deliver(message);
        }
        
        public string submit(string message) {
            return base.Channel.submit(message);
        }
        
        public string report(string message) {
            return base.Channel.report(message);
        }
        
        public string keywordcheck(string message) {
            return base.Channel.keywordcheck(message);
        }
        
        public string blackListCheck(string message) {
            return base.Channel.blackListCheck(message);
        }
    }
}
